---
- hosts: localhost 
  become: true
  connection: local
  tasks:
    - name: Ensure wildfly container is running
      docker_container:
        name: multiply-money
        image: ces-docker.dkrreg.mmih.biz/multiply-money-services:2-1-SNAPSHOT
        state: started
        ports:
          - 8084:8081
